### ISSUE TITLE
Saved models cannot be loaded

### ISSUE THREAD

**Issue by naszka** [prashant-jayan21/minecraft-bap-models#1]
Hi,

I have been trying to load the saved models, and it fails. Looks like the code has been refactored since these models were saved.

```
python generate.py ~/minecraft-bap-models/models/sota_on_augmented_data --saved_dataset_dir=~/minecraft-bap-models/data/augmented --split=test --init_rngs

model = torch.load(f, map_location="cpu")
...
Traceback (most recent call last):
 File "<stdin>", line 2, in <module>
 File "~/miniconda3/envs/minecraft-bap-models/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
  return _load(f, map_location, pickle_module, **pickle_load_args)

 File "~/miniconda3/envs/minecraft-bap-models/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
  result = unpickler.load()
ModuleNotFoundError: No module named 'action_pred_seq'
``` (edited)

**Comment by chrism-qmul** [comment]
Similar issue here:

```
Traceback (most recent call last):
  File "generate.py", line 490, in <module>
    main(args)
  File "generate.py", line 68, in main
    model = torch.load(f)
  File "minecraft-agents/minecraft-bap-models/env/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "minecraft-agents/minecraft-bap-models/env/lib/python3.6/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'seq2seq_attn'
```
